### ISSUE TITLE
MDS packages created from RMD XML files not loading.

### ISSUE THREAD

**Issue by jsibley** [jsibley/convert-rmd-to-iniz#2]
They all give the same error:

```
ERROR - MdsLoader.load(57) |2019-09-27 00:02:50,118| The MDS package could not be imported:
/home/jsibley/openmrs/refapp290iniz/configuration/metadatasharing/Reference_Application_Diagnoses-11.zip
...
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
	at org.openmrs.module.metadatasharing.wrapper.impl.PackageImporterImpl.getImportedItems(PackageImporterImpl.java:120)
	at org.openmrs.module.metadatasharing.task.impl.ImportPackageTask.execute(ImportPackageTask.java:87)
	... 61 more
Caused by: java.lang.NullPointerException
	at org.openmrs.module.metadatasharing.resolver.impl.ObjectByUuidResolver.getExactMatch(ObjectByUuidResolver.java:40)
	at org.openmrs.module.metadatasharing.resolver.impl.ConceptReferenceTermResolver.getExactMatch(ConceptReferenceTermResolver.java:51)
	at org.openmrs.module.metadatasharing.resolver.impl.ConceptReferenceTermResolver.getExactMatch(ConceptReferenceTermResolver.java:29)
	at org.openmrs.module.metadatasharing.resolver.ResolverEngine.resolve(ResolverEngine.java:95)
	at org.openmrs.module.metadatasharing.wrapper.impl.PackageImporterImpl.createImportedItems(PackageImporterImpl.java:217)
	at org.openmrs.module.metadatasharing.wrapper.impl.PackageImporterImpl.getImportedItems(PackageImporterImpl.java:117)```

**Comment by jsibley** [comment]
Turns out that the way I was defining the `concept_reference_term` objects in the MDS package was incorrect (need to fully specify `<conceptSource>` element for the first instance, then "reference" it for future instances).

Fixing that got me past that first error, but now I get this:
```
ERROR - MdsLoader.load(57) |2019-10-03 13:25:31,128| The MDS package could not be imported: /home/jsibley/openmrs/refapp290iniz/configuration/metadatasharing/Reference_Application_Diagnoses-11.zip
...
Caused by: org.openmrs.api.db.DAOException: Error saving org.openmrs.ConceptReferenceTerm [c4091da9-3d7c-37c8-906d-51183e750629]
...
Caused by: org.openmrs.api.APIException: Cannot save 274663001. Failed with the following exception:
...
Caused by: org.hibernate.TransientObjectException: object references an unsaved transient instance - save the transient instance before flushing: org.openmrs.ConceptSource
```
I'm guessing that means that the `concept_reference_term` objects might need to be in their own MDS package that gets run after the one that defines the concept sources?

If I pre-load the concept sources (that are referenced in the first MDS package that gets loaded) into the `concept_reference_source` table, then the MDS packages load just fine.

I either need to find a way to set a load order for the MDS packages (seems to always load them in the same order, but I don't see how it's determining that order) so that I can get the concept sources loaded first, or I need to figure out how to get around that `TransientObjectException`.
